USE [master]
GO

/****** Object:  Database [DB_NEWS]    Script Date: 12.03.2022 12:12:47 ******/
CREATE DATABASE [DB_NEWS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_NEWS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DB_NEWS.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_NEWS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\DB_NEWS.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_NEWS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_NEWS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_NEWS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_NEWS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_NEWS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_NEWS] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_NEWS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_NEWS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_NEWS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_NEWS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_NEWS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_NEWS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_NEWS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_NEWS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_NEWS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_NEWS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DB_NEWS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_NEWS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_NEWS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_NEWS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_NEWS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_NEWS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_NEWS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_NEWS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DB_NEWS] SET  MULTI_USER 
GO

ALTER DATABASE [DB_NEWS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_NEWS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_NEWS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_NEWS] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DB_NEWS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_NEWS] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DB_NEWS] SET  READ_WRITE 
GO


